### ISSUE TITLE
Publish a new release (1.5) with #15 fixed

### ISSUE THREAD

**Issue by atifaziz** [toehead2001/aeroshot#17]
From a usability perspective, I feel [the fix](https://github.com/toehead2001/aeroshot/pull/16) for issue #15 alone warrants a new version as more and more people (well I can certainly speak for myself and I used AeroShot practically everyday) are using higher DPI settings and displays. You can decide whether the new version should be christened 1.5 or 1.4.1.

**Comment by toehead2001** [comment]
Yes, I plan on doing a 1.5 release later today that includes your fix and also the colored Aero Glass feature I've added. I may make a few minor tweaks, and do some quick testing in Windows 10 before I publishing.

I had planed on adding new features only to AeroShot Mini, and just let AeroShot Classic die. However, I suppose I'll add the DPI fix to Classic, and release it as 1.4.1. What do you think?

**Comment by atifaziz** [comment]
I think it should be possible to maintain a single code base with 2 operating modes rather than 2 separate versions, releases and edition labels. When I discovered this fork, it was unnecessary mental tax trying to understand the feature comparison and which version is right for me. I'm guessing it'll be the same for others.

Here's how the operating modes could be consolidated:

- When the application runs, it should run in *classic* mode.
- When closing the main screen, the user should be prompted whether they wish to quit or let the app remain running in the system tray. Depending on the answer, it'll exit or enter the *mini* mode.

**Comment by toehead2001** [comment]
I agree with you, I'll merge them back for v1.6.

At the time, it was just easier to split them up, because of the way I had to make the Tray icon work. When capturing for example, *classic* pulls parameters directly from the GUI, but in *mini* the GUI isn't always around, so it pulls the parameters from the registry (which is why there is Save button in *mini*). There were a few other reasons... I'll probably remember them once I start merging them back together.

I also want place the Window List and Capture button next to each other in the GUI, and then add some sort of separator between them and the settings/parameters.

v1.5 later tonight... Doing some cleanups.

**Comment by toehead2001** [comment]
https://github.com/toehead2001/aeroshot/releases/tag/v1.5.0

**Comment by atifaziz** [comment]
Awesome & thanks! :+1:
