### ISSUE TITLE
Merge the Capture UI back into AeroShot Mini

### ISSUE THREAD

**Issue by toehead2001** [toehead2001/aeroshot#24]
I **always** use the hotkeys for capturing screenshots. That is why I made AeroShot a Tray Icon program and killed the Capture button & window list.

It's useful for some people, so I'll add it back. I really don't want the Capture button & window list in the Settings UI though. I can understand the convenience of it, but they are not settings. Here is my proposed compromise.

![proposal](https://cloud.githubusercontent.com/assets/11582193/8837019/6759e96c-3081-11e5-8b65-5270adfc4111.png)

*Text version if you need to quote something.*
- Create a setting to allow the program to start with the Capture UI open. Tray Icon will always be visible regardless.
- If the program starts with the Capture UI open, we should disable the balloon message on the tray icon.
- When the Capture UI is closed, ask if the user wants to close the whole program, or just the Capture UI window. Offer to remember their choice.

@atifaziz Thoughts, concerns, suggestions?

**Comment by atifaziz** [comment]
I never understood the utility of the window list because I never ran into a scenario where I personally needed it. The only scenario I can imagine for others, speaking theoretically, is to be able to capture a window in its *inactive* state. I would say “window list” can be added back if someone comes back screaming for it. It would also mean that issue #23 wouldn't need fixing.

The system tray with 3 options (Capture UI, Settings and Exit) seems odd and confusing. I'm not sure what you're achieving with keeping the settings dialog absolutely separate. It should be the main screen because that's all there really is to the app. It should do one thing and do it well.

I see the merge as simplification of 2 main use cases and moving between them as intuitively as possible:

1. You want to run the app in the background, providing “aero” screenshot service by principally hijacking the **Alt**+**PrtScn** key.
2. You want to run the app, take screenshots & just quit with zero impact. This is especially useful when you are not at your own computer; where you're taking screenshots on someone else's computer and you have the tool on a network share or a USB stick. This is also why issue #19 is important. So the zero impact here is not polluting the registry and also app doesn't keep running in the background unless required.

I would suggest turning the Settings dialog back into a main screen. It should have a close and a minimize button. Closing the window quits the app (use case 2) and minimizing it sends it to the notification area (use case 1) with the balloon tip that it's still running in the background. I'd even go as far to suggest that perhaps the notification area icon doesn't really need a menu. Double-clicking it should restore the main screen.

When I say *main screen* then naturally we don't need the Save and Cancel buttons. The settings should just be saved on close or minimize. If cancellation is important then a Restore button can be added that will reload setting back (after prompting user for a confirmation). I think there's more danger in forgetting to hit Save then the few times you want to revert settings in such a simple tool.

The app should start in the simple, zero-impact mode. I say this because those who are happy to leave it running in the notification area will do so for days if not weeks on! Asking them to hit minimize after launch is hopefully acceptable. And as you suggested, having a setting to always launch minimized will even take care of that extra click. Bear in mind that the [same can be achieved via Windows shortcuts](http://www.cnet.com/how-to/how-to-automatically-start-a-program-minimized-in-windows/) and without an additional setting.

2¢

**Comment by toehead2001** [comment]
> I would say “window list” can be added back if someone comes back screaming for it.
ok, we are both in an agreement that the window list & capture button should not be added back, at least for now.

I will make a new design proposal later tonight based on some of your feedback.

**Comment by toehead2001** [comment]
Let it die.

**Comment by atifaziz** [comment]
> Let it die

I'm guessing you're referring to the window list here?

What about the rest of suggestions in [my comment](https://github.com/toehead2001/aeroshot/issues/24#issuecomment-124075006) around turning the Settings dialog back into the main screen of the app?

**Comment by toehead2001** [comment]
Yes, I think that's the direction we should go.
Additional thoughts:
-Maybe have the settings autosave in realtime when they're changed in the UI?
-I would like to have the program always start minimized to the tray. However, the first time the program is run, it should open the screenshot settings. I think most people (myself included) rarely change the settings.

**Comment by atifaziz** [comment]
> Maybe have the settings autosave in realtime when they're changed in the UI?

OSX-ish but that's fine.

> I would like to have the program always start minimized to the tray.

The program should follow the user or last usage pattern, if you will. So if it was minimized then it should start that way. If it was closed in its normal state then it should start with the main screen.
